/** Native Base autogenerated imports
* import { Platform } from 'react-native'
* import _ from 'lodash'
*/

import variable from './../variables/platform'

export default (variables = variable) => {
  const cardTheme = {
    '.transparent': {
      shadowColor: null,
      shadowOffset: null,
      shadowOpacity: null,
      shadowRadius: null,
      elevation: null
    },
    '.bordered': {
      borderWidth: variables.borderWidth,
      borderRadius: 2,
      borderColor: variables.cardBorderColor
    },
    '.shadow': {
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 1.5,
      elevation: 3
    },
    marginVertical: 5,
    marginHorizontal: 2,
    flex: 1,
    flexWrap: 'wrap',
    backgroundColor: variables.cardDefaultBg,
    shadowColor: '#000'
  }

  return cardTheme
}
