/** Native Base autogenerated imports
* import { Platform } from 'react-native'
* import _ from 'lodash'
*/

import variable from './../variables/platform'

export default (variables = variable) => {
  /** Native Base autogenerated constants
  * const platformStyle = variables.platformStyle
  * const platform = variables.platform
  */
  const tabTheme = {
    flex: 1,
    backgroundColor: '#FFF'
  }

  return tabTheme
}
