/** Native Base autogenerated imports
* import { Platform } from 'react-native'
* import _ from 'lodash'
*/

import variable from './../variables/platform'

import Colors from '../../Colors'

export default (variables = variable) => {
  const textTheme = {
    fontSize: variables.DefaultFontSize - 1,
    fontFamily: variables.fontFamily,
    color: variables.textColor,
    '.title': {
      color: 'black',
      fontSize: 18
    },
    '.note': {
      color: '#a7a7a7',
      fontSize: variables.noteFontSize
    },
    '.clickable': {
      color: Colors.clickable
    },
    '.centered': {
      textAlign: 'center'
    },
    '.info': {
      fontSize: 10,
      fontWeight: 'bold',
      color: '#a7a7a7'
    }
  }

  return textTheme
}
